defmodule PhiaUi.ThemeCSS do
  @moduledoc """
  Generates CSS custom property declarations from a `%PhiaUi.Theme{}` struct.

  The output is a valid CSS string that can be injected as a `<style>` tag
  in a Phoenix template to apply a custom theme at runtime.

  ## Usage

      theme = PhiaUi.Theme.get!(:blue)
      css = PhiaUi.ThemeCSS.generate(theme)
      # => ":root { --color-primary: oklch(...); ... } .dark { ... }"

  ## Scoped themes (data attribute selectors)

      css = PhiaUi.ThemeCSS.generate_for_selector(theme)
      # => ~s([data-phia-theme="blue"] { ... } .dark [data-phia-theme="blue"] { ... })

  ## All themes in one file

      css = PhiaUi.ThemeCSS.generate_all()
      # => one CSS block per theme, each scoped to its [data-phia-theme] selector

  ## JSON round-trip

      json = PhiaUi.ThemeCSS.to_json(theme)
      theme2 = PhiaUi.ThemeCSS.from_json(json)
  """

  alias PhiaUi.Theme

  @doc """
  Generates a CSS string from a `%PhiaUi.Theme{}`.

  Produces `:root { ... }` for light mode and `.dark { ... }` for dark mode,
  plus a `@theme { ... }` block with radius and typography tokens.

  Accepts an optional keyword list of opts:

  - `:selector` — override the light-mode selector (default: `":root"`)
  - `:dark_selector` — override the dark-mode selector (default: `".dark"`)
  - `:include_theme_block` — whether to emit the `@theme { }` block (default: `true`)

  The output is designed to be injected as a `<style>` tag to override the
  default PhiaUI theme tokens.
  """
  @spec generate(Theme.t(), keyword()) :: String.t()
  def generate(%Theme{} = theme, opts \\ []) do
    selector = Keyword.get(opts, :selector, ":root")
    dark_selector = Keyword.get(opts, :dark_selector, ".dark")
    include_theme_block = Keyword.get(opts, :include_theme_block, true)

    light_vars = color_vars(theme.colors.light)
    dark_vars = color_vars(theme.colors.dark)

    theme_block =
      if include_theme_block do
        """
        @theme {
        #{theme_vars(theme)}}

        """
      else
        ""
      end

    """
    /* PhiaUI Theme: #{theme.label} */
    #{theme_block}#{selector} {
    #{light_vars}}

    #{dark_selector} {
    #{dark_vars}}
    """
  end

  @doc """
  Generates a CSS string scoped to `[data-phia-theme="<name>"]` attribute selectors.

  Unlike `generate/2`, this function does NOT emit an `@theme { }` block, a
  `:root { }` selector, or a standalone `.dark { }` selector. Instead it
  produces two blocks:

  - `[data-phia-theme="<name>"] { ... }` — light-mode custom properties
  - `.dark [data-phia-theme="<name>"] { ... }` — dark-mode custom properties

  This is intended for scoped multi-theme setups where several themes coexist
  on the same page, each applied to a different ancestor element via the
  `data-phia-theme` HTML attribute.
  """
  @spec generate_for_selector(Theme.t()) :: String.t()
  def generate_for_selector(%Theme{} = theme) do
    light_selector = ~s([data-phia-theme="#{theme.name}"])
    dark_selector = ~s(.dark [data-phia-theme="#{theme.name}"])

    light_vars = color_vars(theme.colors.light)
    dark_vars = color_vars(theme.colors.dark)

    """
    /* PhiaUI Theme: #{theme.label} */
    #{light_selector} {
    #{light_vars}}

    #{dark_selector} {
    #{dark_vars}}
    """
  end

  @doc """
  Generates a complete CSS string containing all themes, each scoped to its
  `[data-phia-theme]` attribute selector.

  Accepts:

  - `nil` (default) — uses all built-in presets from `Theme.list/0`
  - a list of atoms (e.g. `[:zinc, :blue]`) — loads named presets
  - a list of `%Theme{}` structs — uses the structs directly

  The output does NOT include any `@theme { }` blocks; those remain in the
  base `theme.css`. The output is sorted alphabetically by theme name for
  deterministic ordering.

  Prepends a header comment explaining how to use the output file.
  """
  @spec generate_all([atom() | Theme.t()] | nil) :: String.t()
  def generate_all(themes \\ nil) do
    resolved =
      themes
      |> resolve_themes()
      |> Enum.sort_by(fn %Theme{name: name} -> name end)

    header = """
    /* PhiaUI Themes — generated by mix phia.theme install
     * Usage: import this file and set data-phia-theme on any ancestor element
     * Example: <html data-phia-theme="blue" class="dark">
     */
    """

    body = Enum.map_join(resolved, "\n", &generate_for_selector/1)

    header <> "\n" <> body
  end

  @doc """
  Serialises a `%PhiaUi.Theme{}` to a JSON string.

  Requires `:jason` as a dependency (available as a transitive dep of Phoenix).
  """
  @spec to_json(Theme.t()) :: String.t()
  def to_json(%Theme{} = theme) do
    theme
    |> Theme.to_map()
    |> Jason.encode!(pretty: true)
  end

  @doc """
  Deserialises a JSON string into a `%PhiaUi.Theme{}`.

  Raises `Jason.DecodeError` for invalid JSON and `KeyError` for missing required fields.
  """
  @spec from_json(String.t()) :: Theme.t()
  def from_json(json) when is_binary(json) do
    json
    |> Jason.decode!()
    |> Theme.from_map()
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  # Normalises the `themes` argument of `generate_all/1` into a list of
  # `%Theme{}` structs.
  defp resolve_themes(nil) do
    Theme.list() |> Enum.map(&Theme.get!/1)
  end

  defp resolve_themes(list) when is_list(list) do
    Enum.map(list, fn
      %Theme{} = theme -> theme
      key when is_atom(key) -> Theme.get!(key)
    end)
  end

  defp color_vars(colors) when is_map(colors) do
    colors
    |> Enum.sort_by(fn {k, _} -> to_string(k) end)
    |> Enum.map_join("", fn {key, value} ->
      css_key = key |> to_string() |> String.replace("_", "-")
      "  --color-#{css_key}: #{value};\n"
    end)
  end

  defp theme_vars(%Theme{} = theme) do
    radius_line = "  --radius: #{theme.radius};\n"

    font_lines =
      theme.typography
      |> Enum.sort_by(fn {k, _} -> to_string(k) end)
      |> Enum.map_join("", fn {key, value} ->
        css_key = key |> to_string() |> String.replace("_", "-")
        "  --#{css_key}: #{value};\n"
      end)

    radius_line <> font_lines
  end
end
